### ISSUE TITLE
Suggestion: ability to order sequences according to a file

### ISSUE THREAD

**Issue by iahdb** [aineniamh/snipit#13]
Hi there,

Really love this tool, thanks for sharing it! :)

I think it would also be really handy to be able to give a specific order for the sequences to appear in (perhaps the same order as the labels csv file?) so it can be easier to compare across predefined conditions rather than closeness to reference.

Thanks :)

**Comment by aineniamh** [comment]
The sequence order is maintained from the order of the input fasta file by default. Reordering that should get you the behaviour you're after!
