### ISSUE TITLE
BUG: Release 1.0.4 on pypa seems to be an outdated code base

### ISSUE THREAD

**Issue by corneliusroemer** [aineniamh/snipit#16]
Installed v1.0.4 and it doesn't behave at all how it should. None of the new arguments appear in help. Maybe you uploaded the wrong zip folder?

<img width="2518" alt="image" src="https://user-images.githubusercontent.com/25161793/161827779-184c5fc2-4fd3-45e7-994d-d10bfa60830e.png">

**Comment by aineniamh** [comment]
Ah yeah I pushed my dev branch, hold on

**Comment by aineniamh** [comment]
https://pypi.org/project/snipit/1.0.5/ 
Resolved

**Comment by corneliusroemer** [comment]
Great thanks :)
