### ISSUE TITLE
Suggestion: Export option as .tsv or .csv !!

### ISSUE THREAD

**Issue by Rezwanuzzaman** [aineniamh/snipit#20]
Hey! @aineniamh , **snipit** is an excellent tool for displaying SNPs. 
It is great that it outputs as .png, but suggesting it should have an option to **export as .tsv or .csv** would really help.
Thanks

**Comment by aineniamh** [comment]
Hi @Rezwanuzzaman, this now exists as the `-s` flag. The figure will be created, but an additional csv file with SNP information will also be created.
