### ISSUE TITLE
snipit for amino acid

### ISSUE THREAD

**Issue by antoine4ucsd** [aineniamh/snipit#26]
is there a way to use snipit for aminoacid alignments? 
it works great with my nt data but I am interested in plotting AA

thank you for this nice program!

**Comment by aineniamh** [comment]
@ammaraziz has been working on this as a feature and it has just been merged in! I'll test it a bit more before tagging a release but feel free to use from the main branch for now!

**Comment by antoine4ucsd** [comment]
thank you!
