### ISSUE TITLE
Coloring reference bases in --recombi-mode

### ISSUE THREAD

**Issue by ktmeaton** [aineniamh/snipit#28]
I'm currently working on integrating your visualization script into my recombination detection tools. I love the `--recombi-mode` option, but since the reference bases aren't colored, it can be difficult to see the breakpoints. 

For example, this command produces the following visualization of **XBF**:

```bash
snipit XBF.fasta \
  --recombi-mode \
  --recombi-references BA.5.2,CJ.1 \
  --reference Reference \
  --flip-vertical \
  --format png \
  --solid-background
```

Alignment: [XBF.fasta.zip](https://github.com/aineniamh/snipit/files/11255965/XBF.fasta.zip) (I've masked non-barcode positions for BA.5.2 and CJ.1)

![recombination_BA 5 2_CJ 1](https://user-images.githubusercontent.com/14981272/232614167-1346a677-0b02-417d-916f-d3118cf2bcfc.png)

But I'd find it more useful if:
1. The reference bases were also colored for each `recombi-reference` (ex. BA.5.2=blue, CJ.1=red)
2. The recombi-references maybe had different saturation for reference versus mutations (ex. reference=light color, mutation = dark color)?

This is a mock-up of a color scheme I'm imagining. Which makes the genomic composition of XBF more clear, and the breakpoints easier to see.

![image](https://user-images.githubusercontent.com/14981272/232615422-ce1a13da-6d80-4277-b030-bed54129fd9d.png)

I'm wondering if you'd also find value (or problems?) with this style of visualization? If you think it's worthwhile, I could experiment in a pull request to see what kind of code changes would be needed?

Thanks for developing this amazing visualizer!

**Comment by ktmeaton** [comment]
My "wish list" for this PR kept growing, to the point that it was outside the scope of this tool. I ended up writing a custom plotting script to achieve the desired effect, so please feel free to close this issue as "off-topic" 🙂

**Comment by aineniamh** [comment]
Hey @ktmeaton, coming to this far too late for it to be useful- I missed both of these (I must have notifications for this repo turned off by accident). Will close now, but glad you got what you needed! Sorry!
