### ISSUE TITLE
Plans for Bioconda?

### ISSUE THREAD

**Issue by rpetit3** [aineniamh/snipit#3]
hi @aineniamh!

This looks really cool and useful! Would it be ok with you if I submitted a recipe to Bioconda?

Cheers,
Robert

**Comment by aineniamh** [comment]
Hi Robert, it's already on bioconda! If you 
`conda install snipit -c bioconda` it should work! Thanks to @tomkinsc!

**Comment by rpetit3** [comment]
Haha probably should have checked first! Thank you!
