### ISSUE TITLE
Option to remove the SNP base and coordinate text from image?

### ISSUE THREAD

**Issue by mlo89** [aineniamh/snipit#34]
Hi,
This tool is very easy and works well on small alignments. Nevertheless, when visualising larger alignments the image becomes messy with the text of the bases in each tile as well as the coordinates on the top.  Would it be possible to have an option to remove these elements? 
Thanks!

**Comment by mlo89** [comment]
I found a quick not-clean solution: removing the blocks of text corresponding to the bases via opening the svg in vim. The bases are located in the block between the reference genome and the last genome of your list of sequences. Then just by highlighting all those blocks and deleting them, I obtain an image without the text for bases and coordinates.

**Comment by aineniamh** [comment]
I've now added an option for `--remove-site-text` that only includes the labels on the bottom and left hand side. Available on the main branch and will include in the next release!
