### ISSUE TITLE
Snipit on a.acids

### ISSUE THREAD

**Issue by woguta** [aineniamh/snipit#42]
I was investigating snps in my sequence data, but got a challenge with amino acids/protein sequences. Seems like snipit only works well with nucleotides (4 bases), can snipit be extended to work with protein sequences as well? I noticed that only amino acids with the same letters as nucleotide bases were the only ones being picked. Merci.

**Comment by woguta** [comment]
Or has it been implemented?

**Comment by aineniamh** [comment]
If you specify `--sequence-type aa` it should run in amino acid mode, but otherwise will default assume your alignment is nucleotides!

**Comment by woguta** [comment]
Okay, thank you for this. Merci

**Comment by aineniamh** [comment]
No worries!
