### ISSUE TITLE
code request

### ISSUE THREAD

**Issue by Aria-Dolatabadian** [aineniamh/snipit#44]
Hi @aineniamh 
I am trying to figure out how to use the code. Would you please provide me the code to run in Pycharm? 
Thanks
Aria

**Comment by aineniamh** [comment]
Hi @Aria-Dolatabadian, snipit is a command line tool and can be installed using pip. If you want to run that within pycharm you could try [this](https://stackoverflow.com/questions/28570058/running-command-line-commands-within-pycharm#:~:text=Press%20Alt%2BF12%20to%20open,to%20run%20and%20press%20enter.). All the code is open source and available here on the GitHub.
