### ISSUE TITLE
snipit --flip-vertical feature not working as intended

### ISSUE THREAD

**Issue by clmattson** [aineniamh/snipit#45]
Hello!

Loving snipit so far! However, I have noticed that the `--flip-vertical` option doesnt seem to be working. When I add this flag, the output image file is in the same orientation as before (reference at the bottom and sequences in reverse order compared to the input FASTA) , and additionally the annotations on the mutation squares are removed (ie the plot has axis labels and sequence labels, but no text). I'd love to utilize this feature if possible! Below is the code I have tried. I attempted this with an svg and png outputs. 

This code makes a beautiful plot, and has the reference at the bottom: 
`snipit --sequence-type nt -o pac_parents_NCR_labeled_snipit -f svg --labels all_cotr_NCR_labels.csv pac_phi6_prelim_mutation_analysis_1_all_seqs_5pNCRONLY_subalign.fasta`

When I try to add the `--flip-vertical` flag, it no longer works as intended. 
`snipit --flip-vertical --sequence-type nt -o pac_parents_NCR_labeled_flipped_snipit -f svg --labels all_cotr_NCR_labels.csv pac_phi6_prelim_mutation_analysis_1_all_seqs_5pNCRONLY_subalign.fasta`
No warnings or errors are produced. below is the output of the code:
```
Note: assuming the alignment provided is of type nt. If this is not the case, change input --sequence-type
Snipping Complete: C:\Users\cmatt\Documents\phi6_reverse_genetics\pac_mutation_analysis\pac_parents_NCR_labeled_flipped_snipit.svg
```

Best,
Courtney
'

**Comment by aineniamh** [comment]
Hi @clmattson, I believe this should be resolved now, there was an issue with the ordering of arguments that had been introduced in a recent update! Thanks for your patience with this! If there's still any problem, just let me know and I can reopen the issue.
