### ISSUE TITLE
ModuleNotFoundError: No module named 'snp_functions'

### ISSUE THREAD

**Issue by Pepaflores56** [aineniamh/snipit#5]
I have trying to run snipit from a conda environment in Windows 10 and in Linux but I get the subject error. I have checked the snipt files and the "snp_funcitons" is there. Any light on why this is happening? 
File "c:\users\xxxx\appdata\local\conda\conda\envs\snipit\lib\site-packages\snipit\command.py", line 9, in <module>
import snp_functions as sfunks

**Comment by aineniamh** [comment]
Hi @Pepaflores56, I'm really not very familiar with Window's systems- but I think I've gotten to the problem in snipit. I've added a change to the master here that I think should resolve it! Hope it helps!
